### ISSUE TITLE
Links keep leading and trailing spaces creating inconsistencies

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#123]
**Version**
0.4.1

**Current behavior**
When you create links on a node's body, the link keeps heading and trailing spaces creating inconsistencies on syntax highlighting of the links. See behavior below:

![trim](https://user-images.githubusercontent.com/6022674/77894470-9bde5200-7275-11ea-8a16-d6733f4f637d.gif)

**Expected behavior**
Links are normalized on node save so that they keep consisten.

**Comment by blurymind** [comment]
One thing to note is that Yarn is using a library called bondagejs to preview stories. That feature is currently disabled, but its something that I want to bring back.

Bondagejs does not like it when node titles contain trailing spaces or any spaces actually.

So not creating a link to a node when the link has them is actually a good thing here, because the user can see that the link will not work

**Comment by daviddq** [comment]
Yep... I saw an issue related to the "run story" feature and have been looking for it on all branches/forks. Having such a feature would be great for my designer :)

"node titles" and "link titles" should be trimmed so non of them contain heading nor trailing spaces. Don't you think so?

**Comment by blurymind** [comment]
Yes I agree they should :) 

The feature was there at one point, but only worked on the electron version. I disabled it when I refactored yarn to also be a progressive web app.
There is actually code to run it as another electron window, but it needs to be refactored to run the preview inside the edit node dialogue window I think

**Comment by daviddq** [comment]
Fixed in PR #121
